### ISSUE TITLE
error initializing Firestore

### ISSUE THREAD

**Issue by henriqueweiand** [n6g7/redux-saga-firebase#123]
![captura de tela 2018-07-12 as 18 31 11](https://user-images.githubusercontent.com/6539492/42660554-ecf69088-8601-11e8-834c-99ff2c938e6a.png)

My code:

```js
import firebase from 'firebase/app';
import '@firebase/firestore';
import auth from 'firebase/auth';
// import database from 'firebase/database';
import ReduxSagaFirebase from 'redux-saga-firebase';

import config from './config';

const firebaseApp = firebase.initializeApp(config);
const reduxSagaFirebase = new ReduxSagaFirebase(firebaseApp);

export { reduxSagaFirebase, firebase, auth };
```

**Comment by n6g7** [comment]
Hey @henriqueweiand,

That looks like a warning from the firestore library about a (upcoming? not sure...) breaking change. Did you notice any actual error in your app?

**Comment by n6g7** [comment]
Ah ok so this has to do with the [new defaults](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#~timestampsInSnapshots) of the firestore SDK to return dates as [Timestamp](https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp) instead of Date.

So this is a deprecation warning from Firebase, nothing to do with RSF. :)
