### ISSUE TITLE
syncCollection causes redux dev tools to crash

### ISSUE THREAD

**Issue by doelgonzo** [n6g7/redux-saga-firebase#127]
I've been struggling with this for some time now, and the situation I've run into is that a block of code like this will work just fine

```javascript
function* myListSaga() {
  yield takeLatest(
    'MY_LIST_SYNC',
    function* doSync() {
      const snapshot = yield call(rsf.firestore.getCollection, 'myList');
      yield put(onMyListChanged(snapshot));
    },
  );
```

but when trying the following, redux dev tools crashes:

```javascript
function* myListSaga() {
  yield takeLatest(
    'MY_LIST_SYNC',
    function* doSync() {
      yield fork(
         reduxSagaFirebase.firestore.syncCollection, 
         'myList',
         { successActionCreator: onMyListChanged }
      );
    },
  );
```

These sagas are kicked off soon after the page renders, as the user lands on a page that dispatches the MY_LIST_SYNC actions.

Now, to reproduce... I had redux dev tools open, and then I landed on this page... it would often just crash then and there, but sometimes it would happen just when dispatching an action right after landing here and having the changed actions be triggered.

Now, if I had the chrome (or firefox) inspector closed... landed on this page, I **could** run into scenarios where the actions all appeared fine on the console and I could go about my business, but as soon as I dispatched a new action it failed.

**Note**, I did also try with the following and the result was no different.

```javascript
function* myListSaga() {
  yield take('MY_LIST_SYNC');
  yield fork(
    reduxSagaFirebase.firestore.syncCollection,
    'myList',
    { successActionCreator: onMyListChanged },
  );
}
```

I am ok with using the getCollection for now and periodically polling it for changes... but the heavy-handedness of that is sickening. Keeping the client update with the latest firestore data is the goal here, especially when reacting to remote changes (i.e. a conversation or group chat, for example)

Any particular ideas here? I may just be missing a step but I thought I covered what was included in the docs per se

**Comment by n6g7** [comment]
Hi @doelgonzo, sorry for not getting back to you sooner.

Thanks for looking into this. One of firestore API's weaknesses is that it cannot "stream" new documents in a collection: using `rsf.firestore.syncCollection(ref)` always return the entire collection after a new document has been added to a collection (or at least I couldn't find it in the docs). In comparison, the realtime database's `rsf.database.sync` method can be configured to only return new children (by setting `event` to "child_added").

So if you're using firestore for a group chat (as per your example) or any realtime, read-heavy application, you'll have to reload the entire history of messages everytime there is a new post, which is very inefficient and quickly creates very large redux actions which apparently causes redux-devtools to crash.

One potential solution would be to use a query instead of a collection reference, but I've never tried that so I can't vouch for it:
```js
function* myListSaga() {
  yield takeLatest(
    'MY_LIST_SYNC',
    function* doSync() {
      // Only load documents created in the last 10 minutes
      const query = firestoreApp.firestore().collection('myList').where('date', '>=', new Date() - 10*60*1000)
      yield fork(
         reduxSagaFirebase.firestore.syncCollection, 
         query,
         { successActionCreator: onMyListChanged }
      );
    },
  );
```

Hope that helps!

**Comment by doelgonzo** [comment]
Ah! I see. So, perhaps the first request can be a getCollection and store a timestamp of the get, and do subsequent syncCollection calls with a where. The initial load is likely to be the huge once, but subsequent ones should be much much smaller

**Comment by n6g7** [comment]
Yep, hopefully that'll solve your problem.

I'll close this for now but don't hesitate to re-open if the problem persists. :)
