### ISSUE TITLE
listing files by folders in storage

### ISSUE THREAD

**Issue by henriqueweiand** [n6g7/redux-saga-firebase#140]
I am uploading files using storage and I noticed that there is no possibility to open a channel to monitor the changes of a storage endpoint.

I implemented a folder structure where the id of the person is the reference of the folder in the storage, so I would like to list all the files saved there even when there are new submissions, finally a common listener.

How could this situation be dealt with today? I've thought about making a new table in the firestore to save the endpoints of the images in the storage, but I see that this would not be the best exit ...

![captura de tela 2018-09-05 as 13 44 27](https://user-images.githubusercontent.com/6539492/45108025-d91e4480-b111-11e8-8ac1-728378750ee7.png)

In folder:

![captura de tela 2018-09-05 as 13 50 49](https://user-images.githubusercontent.com/6539492/45108350-bf313180-b112-11e8-9c7f-3d2ffe2a3d92.png)

**Comment by n6g7** [comment]
Hi Henrique,

Sorry for the late response, I've looked into it and I don't think that Firebase natively supports "listening" on a storage references unfortunately. Maybe you could open a feature request with them. :)

In the meantime, I think you can either:
- index the uploaded files in a firestore table (as you described) and use firestore channel
- or create a cloud function that listens for storage event and [send a message using Firebase Messaging](https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendToTopic), that way you can use a [messaging channel](https://redux-saga-firebase.js.org/reference/dev/messaging#channel) in your frontend.

Hope this helps!
I'm closing this issue for now since I don't there's anything we can do in RSF to solve your problem unfortunately.
