### ISSUE TITLE
AaD I can receive null or undefined values via database channel.

### ISSUE THREAD

**Issue by n6g7** [n6g7/redux-saga-firebase#36]
Redux-saga does not support null or undefined values being emitted in a channel:
> Note: You need to sanitize your event sources as to not pass null or undefined through the event channel. While it's fine to pass numbers through, we'd recommend structuring your event channel data like your redux actions. { number } over number.
- [source](https://redux-saga.js.org/docs/advanced/Channels.html#using-the-eventchannel-factory-to-connect-to-external-events)

The recommended solution is to format the channel like a redux action (object with keys). We could have a "data" key to pass the result.

**Comment by ryansully** [comment]
I actually encountered this issue while writing unit tests for my revamped `channel()` method. I can either submit a PR with this specific solution, or with the entire new method (sneak peek here: https://github.com/ryansully/firecards/blob/master/src/firebase/database.js).

**Comment by n6g7** [comment]
@ryansully That's really cool, I like the `pathOrRef` and `buffer` options.

I wrote a first fix over at https://github.com/n6g7/redux-saga-firebase/pull/40 (I stole the `snapshot` and `value` keys from your implementation 😉), as I'd rather add the `pathOrRef` argument to every method at once rather than just on this one.

... which reminds that now that #31 is merged, https://github.com/n6g7/redux-saga-firebase/issues/34 is ready for you to tackle if you want. :)

**Comment by ryansully** [comment]
Ah, you combined `snapshot` and `value` in the same response. I had them as separate responses by a `returnSnapshot` argument, since `value` is already available if you return the snapshot, but that works too. Just don't forget the corresponding unit tests (I wrote them in https://github.com/ryansully/firecards/blob/master/src/firebase/database.test.js). If you move forward with the combined response, I think the branch case in one of them will need to be modified or combined into one test.

I had wanted to get the codebase fully covered before proceeding with #34. I'll follow up with that issue first.
