### ISSUE TITLE
Add listener in loop

### ISSUE THREAD

**Issue by tamal-appsbee** [n6g7/redux-saga-firebase#47]
Hi,

How I can add firebase on('value') listener in a loop. For example :
I have user path in firebase and I want to attach listeners for specific users only, I have an array of use keys.

**Comment by n6g7** [comment]
Hi @tamal-appsbee,

There are two ways of synchronising your redux store with the Firebase real-time database using RSF:

- **Create a channel and `take` from it**
  This is the manual solution, it's good if you need a custom workflow.
  ```js
  import { syncTodos } from '../actionCreators/todos';

  function* syncTodosSaga() {
    const channel = yield call(rsf.database.channel, 'todos');

    while(true) {
      const { value: todos } = yield take(channel);
      yield put(syncTodos(todos));
    }
  }

  function* rootSaga() {
    yield fork(syncTodosSaga);
  }
  ```
- **Use the [`database.sync`](https://n6g7.github.io/redux-saga-firebase/reference/database#sync) method**
  This does exactly the same as the manual solution but you don't have to do it youself. :)
  ```js
  import { syncTodos } from '../actionCreators/todos';

  function* rootSaga() {
    yield fork(rsf.database.sync, 'todos', syncTodos);
  }
  ```

Those two examples give **exactly the same result** because `database.sync` is simply a helper function around `database.channel` and `take`.

Does that help?
