### ISSUE TITLE
unsubscribe from database reference

### ISSUE THREAD

**Issue by nagygergo** [n6g7/redux-saga-firebase#59]
Hi!

In the current documentation, I don't see a way to unsubscribe from a database reference. Is there a way that I don't see, or is this a yet to be implemented feature. Also, I would be glad to help to implement it.

[Firebase docs for databaseRef.off()](https://firebase.google.com/docs/reference/js/firebase.database.Reference#off)

**Comment by n6g7** [comment]
Hi @nagygergo :)

Actually the unsubscription is implemented as part of the `database.channel()` method ([see the code here](https://github.com/n6g7/redux-saga-firebase/blob/master/src/database.js#L48)). Since this is the only place where we do any database subscription, I don't see why we'd need to add more support for unsubscription.
What is your use case exactly?

As a general rule of thumb, this package is intended to be used alongside the firebase SDK itself, not in replacement of it. So if you are doing "manual" subscription with the SDK (`ref.on('value', callback)`) then it's absolutely fine to unsubscribe with the SDK as well (`ref.off('value', callback)`). 😉

Hope that helps!

**Comment by nagygergo** [comment]
If that's the case, I may have misunderstood the workings of `database.sync(path, actionCreator)`.

Thanks for the clarification!
