### ISSUE TITLE
Listening to the same channel a 2nd time does not work

### ISSUE THREAD

**Issue by EdmundMai** [n6g7/redux-saga-firebase#67]
I have this code to listen to my channel:

```
  yield all([
    reduxSagaFirebase.database.sync(
      `users/${user.id}/orders`,
      userActions.historyFetchSuccess
    )
  ]);
```

This runs every time a user signs in.

However, when I:
1. Sign in with User 1
2. Sign out
3. Sign in with User 2
4. Sign out
5. Sign in with User 1

The saga does not `yield` on the last step. My hunch is because it has listened to that path before, and breaks for some reason if it tries to listen to it again

If I change the path to something unique (just to prove that this is the issue), it works every time:

```
 const date = moment().valueOf(); // just current time in seconds
 yield all([
   reduxSagaFirebase.database.sync(
     `users/${user.id}/orders-${date}`,
     userActions.historyFetchSuccess
   )
 ]);
```

**Comment by EdmundMai** [comment]
Never mind it was my problem, I had 2 separate sagas, this is how I fixed it

```
 yield takeLatest(
   [actions.APP.START, actions.USER.SIGN_IN_SUCCESS],
   fetchOrderHistory
 );
```

**Comment by EdmundMai** [comment]
Seems to still be an issue...

**Comment by n6g7** [comment]
Hi @EdmundMai,

I think your second comment is right: running `yield all(...)` every time a user signs in will start new sagas **but not stop the previously started ones**. So, after you log in with user 2, the sagas for user 1 are still running and, when you re-login with user 1, you're attempting to open a second channel to the same endpoint (`users/${user1.id}/orders`) which Firebase does not support.

Using `takeLatest` instead of `all` is the solution as it will stop the previously running sagas before starting the new ones. :)

If you're still having this issue, can you please share a code example for something that's not working as expected? :)

**Comment by EdmundMai** [comment]
Looks like after updating to the latest version and updating the arguments it works:

yield all([
  reduxSagaFirebase.database.sync(
    `/users/${CONFIG.APP_ID}/${user.id}/orderHistory`,
    {
      transform: firebaseValue => {
        ...

        return { ... };
      },
      successActionCreator: userActions.orderHistoryFetchSuccess,
      failureActionCreator: userActions.orderHistoryFetchFailure
    }
  )
]);
