### ISSUE TITLE
Subfunctions for filtering data

### ISSUE THREAD

**Issue by blacktea** [n6g7/redux-saga-firebase#79]
Would be nice to have subfunctions for adding filters

```
.database().ref('items').orderByChild('owner').equalTo(uid);
```

**Comment by n6g7** [comment]
Hey @blacktea,

I think this actually already would work in a similar way to what's described in the [sorting and filtering for firestore docs](https://n6g7.github.io/redux-saga-firebase/guides/sorting-filtering).

Similarly to firestore, the realtime database, [`once`](https://firebase.google.com/docs/reference/js/firebase.database.Query#once), [`on`](https://firebase.google.com/docs/reference/js/firebase.database.Query#on) and [`off`](https://firebase.google.com/docs/reference/js/firebase.database.Query#off) methods exist for [Reference](https://firebase.google.com/docs/reference/js/firebase.database.Reference) and [Query](https://firebase.google.com/docs/reference/js/firebase.database.Query) objects.
This means we can re-use [`database.read`](https://n6g7.github.io/redux-saga-firebase/reference/database), [`database.channel`](https://n6g7.github.io/redux-saga-firebase/reference/database#channel) and [`database.sync`](https://n6g7.github.io/redux-saga-firebase/reference/database#sync) with Query objects instead of References!

Examples:

```js
// Will synchronise ALL items:
yield fork(rsf.database.sync, 'items', action)
```

can become:

```js
// Will only synchronise items belonging to a specific owner:
yield fork(
  rsf.database.sync,
  db.ref('items').orderByChild('owner').equalTo(uid),
  action
)
```

Similarly it is possible to order and limit queries:

```js
// Get the 10 smallest items:
const users = yield call(
  rsf.database.read,
  db.ref('items').orderBy('size').limit(10)
)
```

I have never actually tried these so I'm not sure this will work, but it looks promising.
I suggest you try this approach and we'll make changes to the lib / add a section to the docs depending on the result! 😀

**Comment by TimMeade** [comment]
i have tried to get this to work using firestore and have hit a wall.   Does anyone have a full example?

**Comment by n6g7** [comment]
@TimMeade I don't have any right now but I'll try to build one over the next couple weeks. :)

**Comment by n6g7** [comment]
@TimMeade I added a doc on [using custom keys](https://n6g7.github.io/redux-saga-firebase/guides/custom-keys), feel free to re-open this issue if you have any other question. :)
