### ISSUE TITLE
Getting Custom User Data

### ISSUE THREAD

**Issue by LukeSmetham** [n6g7/redux-saga-firebase#96]
Hey,

First of all, thanks for such a useful repo! 

Sorry if this is a stupid/easy question but I've become really stuck with it...

I am using Firestore and have custom user data saved in a 'Users' Collection. When I use the provided auth channel to get a users auth status, how can I also initiate another channel for syncing their user data from the 'Users' collection?

**Comment by n6g7** [comment]
Hi Luke,

It sounds like you need to start a new "sync" saga whenever a user logs in.
You can do so by listening for the login action:

```js
// This is the saga that runs every time a user logs in
// It syncs the data of the current user
function * syncUserData (action) {
  yield fork(
    rsf.firestore.syncDocument,
    `Users/${action.user.uid}`,
    {
      successActionCreator: syncUserData
    }
}

// This is the saga that listens for user logins
// It should always run, so fork it in your root saga
// When a user logs in, it any running `syncUserData` saga (if there is any) and starts a new one with the dispatched action
function * listenForSignIn () {
  yield takeLatest(
    'LOGIN', // or whatever type you use for your login action
    syncUserData
}
```

Assuming you have an action being dispatched whenever a user logs in (we use `LOGIN` above but it could be anything), then this should do most of what you want.

However there's one case that isn't handled here: when a user logs out, then `syncUserData` saga will continue to run and throw errors because the user no longer has permission to read the data.
You can find a detailed explanation and solution here: https://github.com/n6g7/redux-saga-firebase/issues/92#issuecomment-356932653

Let me know if that fixes your problem!

**Comment by n6g7** [comment]
Hey @LukeSmetham, haven't heard back from you so I'm assuming your problem is solved. I'm closing this issue for now but let me know if you have any further question. 🙂
